spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false #osiv
    properties:
      hibernate:
        ddl-auto: validate
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 3
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_HOST}
    password: ${EMAIL_HOST_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.hibernate.or.jdbc.bind: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.transaction: DEBUG
jwt:
  secret: ${SECRET_KEY}
email:
  domain: ${EMAIL_DOMAIN}
  url: ${EMAIL_URL}
request:
  domain: ${REQUEST_DOMAIN}